version: '3.8'

services:
  backend:
    build: ./backend
    container_name: go_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint: ["/app/script.sh"]
    command: ["./main"]
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb

  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    ports:
      - "80:80"

volumes:
  db_data:
