version: '3.8'

services:

  db:
    build:
      context: ./db-init
    container_name: allchat-database
    ports:
      - "3306:3306"
    networks:
      - chat-network
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/

  frontend:
    container_name: allchat-frontend
    build:
      context: ./front-end
    ports:
      - "443:443"
    networks:
      - chat-network
    depends_on:
      - backend
 
  backend:
    container_name: allchat-backend
    build:
      context: ./back-end
    ports:
      - "8443:8443"
    depends_on:
      - db
    networks:
      - chat-network
    volumes:
      - ./back-end/logs:/app/logs

networks:
  chat-network:
    driver: bridge

volumes:
  db-data:
    driver: local