version: '3.8'

services:

  db:
    build:
      context: ./db-init
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
 
  backend:
    build:
      context: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
