version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
